blueprint:
  name: Deconz Dresden Switch as dimmer for WLED strip
  description: Use a Deconz Dresden Elektronik Lighting Switch as general purpos dimmer for a WLED light strip (segment)
  domain: automation
  input:
    deconz_switch:
      name: Dimmer source
      description: Deconz Dresden Elektronik Lighting Switch
      selector:
        device:
    deconz_button:
      name: Deconz button
      description: Which button for the selected switch
      default: 'Left (or single)'
      selector:
        select:
          options:
            - 'Left (or single)'
            - 'Right'
    wled_light:
      name: Light strip
      description: WLED light strip (segment) to control
      selector:
        entity:
          integration: wled
          domain: light
    step_delay:
      name: Transition step lenght
      description: Length of each transition step in milliseconds (dim speed)
      default: 100
      selector:
        number:
          min: 10
          max: 250
          step: 10
          unit_of_measurement: 'ms'
    on_brightnes:
      name: Brightnes in % for ON button
      description: Optional brightness value to send when turning the strip on (0 = disabled).
      default: 0
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: '%'

mode: restart
condition: [ ]

trigger:
  - device_id: !input deconz_switch
    domain: deconz
    platform: device
    type: remote_button_short_release
    subtype: turn_on
    id: turnOnLeft
  - device_id: !input deconz_switch
    domain: deconz
    platform: device
    type: remote_button_long_press
    subtype: turn_on
    id: dimUpStartLeft
  - device_id: !input deconz_switch
    domain: deconz
    platform: device
    type: remote_button_long_release
    subtype: turn_on
    id: dimUpStopLeft

  - device_id: !input deconz_switch
    domain: deconz
    platform: device
    type: remote_button_short_release
    subtype: dim_up
    id: turnOffLeft
  - device_id: !input deconz_switch
    domain: deconz
    platform: device
    type: remote_button_long_press
    subtype: dim_up
    id: dimDownStartLeft
  - device_id: !input deconz_switch
    domain: deconz
    platform: device
    type: remote_button_long_release
    subtype: dim_up
    id: dimDownStopLeft

  - device_id: !input deconz_switch
    domain: deconz
    platform: device
    type: remote_button_short_release
    subtype: dim_down
    id: turnOnRight
  - device_id: !input deconz_switch
    domain: deconz
    platform: device
    type: remote_button_long_press
    subtype: dim_down
    id: dimUpStartRight
  - device_id: !input deconz_switch
    domain: deconz
    platform: device
    type: remote_button_long_release
    subtype: dim_down
    id: dimUpStopRight

  - device_id: !input deconz_switch
    domain: deconz
    platform: device
    type: remote_button_short_release
    subtype: turn_off
    id: turnOffRight
  - device_id: !input deconz_switch
    domain: deconz
    platform: device
    type: remote_button_long_press
    subtype: turn_off
    id: dimDownStartRight
  - device_id: !input deconz_switch
    domain: deconz
    platform: device
    type: remote_button_long_release
    subtype: turn_off
    id: dimDownStopRight

variables:
  deconz_button: !input deconz_button
  wled_light: !input wled_light
  on_brightnes: !input on_brightnes
  dim_values:
    [ 1,2,3,4,5,6,7,8,9,10,12,14,16,18,20,22,24,26,28,30,34,38,42,46,50,54,58,62,66,70,78,86,94,100,108,116,124,130,144,160,176,192,208,224,240,250 ]
  brightness_value: |
    {{ state_attr(wled_light, 'brightness') or 0 | int }}
  dim_values_up: |
    {{ dim_values | select("greaterthan", brightness_value) | list }}
  dim_values_down: |
    {{ dim_values[::-1] | select("lessthan", brightness_value) | list }}

action:
  - choose:
      - conditions:
          - condition: trigger
            id: turnOnLeft
          - condition: template
            value_template: |
              {{ deconz_button != 'Right' }}
          - condition: template
            value_template: |
              {{ on_brightnes > 0 }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input 'wled_light'
            data:
              brightness: !input 'on_brightnes'
      - conditions:
          - condition: trigger
            id: turnOnLeft
          - condition: template
            value_template: |
              {{ deconz_button != 'Right' }}
          - condition: template
            value_template: |
              {{ on_brightnes == 0 }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input 'wled_light'

      - conditions:
          - condition: trigger
            id: turnOnRight
          - condition: template
            value_template: |
              {{ deconz_button == 'Right' }}
          - condition: template
            value_template: |
              {{ on_brightnes > 0 }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input 'wled_light'
            data:
              brightness: !input 'on_brightnes'
      - conditions:
          - condition: trigger
            id: turnOnRight
          - condition: template
            value_template: |
              {{ deconz_button == 'Right' }}
          - condition: template
            value_template: |
              {{ on_brightnes == 0 }}
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input 'wled_light'

      - conditions:
          - condition: trigger
            id: turnOffLeft
          - condition: template
            value_template: |
              {{ deconz_button != 'Right' }}  
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input 'wled_light'

      - conditions:
          - condition: trigger
            id: turnOffRight
          - condition: template
            value_template: |
              {{ deconz_button == 'Right' }}  
        sequence:
          - service: light.turn_off
            target:
              entity_id: !input 'wled_light'

      - conditions:
          - condition: trigger
            id: dimUpStartLeft
          - condition: template
            value_template: |
              {{ deconz_button != 'Right' }}  
          - condition: state
            entity_id: !input 'wled_light'
            state: 'on'
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: '{{ repeat.index <= (dim_values_up | length) }}'
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input 'wled_light'
                  data:
                    brightness: '{{ dim_values_up[repeat.index - 1] }}'
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: !input step_delay

      - conditions:
          - condition: trigger
            id: dimUpStartRight
          - condition: template
            value_template: |
              {{ deconz_button == 'Right' }}  
          - condition: state
            entity_id: !input 'wled_light'
            state: 'on'
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: '{{ repeat.index <= (dim_values_up | length) }}'
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input 'wled_light'
                  data:
                    brightness: '{{ dim_values_up[repeat.index - 1] }}'
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: !input step_delay

      - conditions:
          - condition: trigger
            id: dimDownStartLeft
          - condition: template
            value_template: |
              {{ deconz_button != 'Right' }}  
          - condition: state
            entity_id: !input 'wled_light'
            state: 'on'
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: '{{ repeat.index <= (dim_values_down | length) }}'
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input 'wled_light'
                  data:
                    brightness: '{{ dim_values_down[repeat.index - 1] }}'
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: !input step_delay

      - conditions:
          - condition: trigger
            id: dimDownStartRight
          - condition: template
            value_template: |
              {{ deconz_button == 'Right' }}  
          - condition: state
            entity_id: !input 'wled_light'
            state: 'on'
        sequence:
          - repeat:
              while:
                - condition: template
                  value_template: '{{ repeat.index <= (dim_values_down | length) }}'
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: !input 'wled_light'
                  data:
                    brightness: '{{ dim_values_down[repeat.index - 1] }}'
                - delay:
                    hours: 0
                    minutes: 0
                    seconds: 0
                    milliseconds: !input step_delay
